### ISSUE TITLE
Request thread UI

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/dashboard#21]
This UI will be shown to the user when they open an existing request. 

It should show a thread of messages and the option to answer in the end.

Each message is a expandable tile. When closed it shows the first line with ellipsis. 

When it is open it shows the whole content. 

In the end there is a form to submit an answer in the thread.

**Comment by MiroBenicio** [comment]
the final screen will be different, since primevue does not give fieldset component personalization (the message) in the UI kit. 

<img width="853" alt="Captura de Tela 2024-07-04 às 11 21 49" src="https://github.com/mytiki/dashboard/assets/96149507/40e1888d-16d9-44a4-a0c4-9dcb14b8190c">
